
export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className="">
      <h1 className="">Home Page</h1>
    </div>
  );
}
