import PostDetails from "@/components/postdetails";
import SuspenseJsx from "@/components/suspenseJsx";
import Link from "next/link";
import { Suspense } from "react";

export const metadata = {
  title: "Post Details",
  description: "Generated by create next app",
};

export default async function PostPage({params}) {

    return (
        <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto">
                <Link 
                    href='/posts'
                    className="inline-flex items-center text-gray-600 hover:text-gray-900 font-medium mb-8 transition-colors duration-200 group"
                >
                    <svg className="w-5 h-5 mr-2 group-hover:-translate-x-1 transition-transform duration-200" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                    </svg>
                    Back to Posts
                </Link>

                <div className="mb-8">
                    <h1 className="text-4xl font-bold text-gray-900 mb-2">Post Details</h1>
                </div>
               <Suspense fallback={<SuspenseJsx/>}>
                    <PostDetails postId={params.id?.trim()}/>
                </Suspense>
            </div>
        </div>
    );
}