import Link from "next/link";

export const metadata = {
  title: "Post Details",
  description: "Generated by create next app",
};

export default async function PostDetails({postId}) {

    const response = await fetch(`https://jsonplaceholder.typicode.com/posts/${postId}`, {
        next: {
            revalidate: 120
        }
    });

    const post = await response.json();

    if(!post || !post.id) {
        return (
            <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 py-12 px-4 sm:px-6 lg:px-8">
                <div className="max-w-3xl mx-auto">
                    <div className="bg-red-50 border border-red-200 rounded-lg p-8 text-center">
                        <svg className="w-16 h-16 text-red-400 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                        </svg>
                        <h2 className="text-2xl font-bold text-gray-800 mb-2">Post Not Found</h2>
                        <p className="text-gray-600 mb-6">There is no post with ID: {postId}</p>
                        <Link 
                            href='/posts'
                            className="inline-flex items-center px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg transition-colors duration-200"
                        >
                            <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                            </svg>
                            Back to Posts
                        </Link>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <article className="bg-white rounded-xl shadow-lg overflow-hidden">
            <div className="bg-gradient-to-r from-blue-600 to-purple-600 px-8 py-12">
                <div className="flex items-center text-white text-sm mb-4 opacity-90">
                    <span className="bg-white bg-opacity-20 px-3 text-blue-600 py-1 rounded-full">
                        Post #{post.id}
                    </span>
                </div>
                <h2 className="text-3xl md:text-4xl font-bold text-white leading-tight">
                    {post.title}
                </h2>
            </div>

            <div className="px-8 py-10">
                <div className="prose prose-lg max-w-none">
                    <p className="text-gray-700 leading-relaxed text-lg">
                        {post.body}
                    </p>
                </div>

                <div className="mt-10 pt-6 border-t border-gray-200">
                    <div className="flex items-center justify-between">
                        <div className="flex items-center text-gray-500 text-sm">
                            <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                            </svg>
                            User ID: {post.userId}
                        </div>
                        <Link 
                            href='/posts'
                            className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg transition-colors duration-200"
                        >
                            View All Posts
                        </Link>
                    </div>
                </div>
            </div>
        </article>
    );
}